// <auto-generated />
using BookStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Persistence.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20220912151136_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStore.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CreationYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 30,
                            Author = "Martin Gilbert",
                            CreationYear = "2004",
                            Genre = "History",
                            Price = 25.55m,
                            Title = "The First World War: A Complete History"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100,
                            Author = "Plato",
                            CreationYear = "2021",
                            Genre = "Philosophy",
                            Price = 5m,
                            Title = "The Republic"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 45,
                            Author = "Andrew Lock",
                            CreationYear = "2021",
                            Genre = "Programming",
                            Price = 36.39m,
                            Title = "ASP.NET Core in Action, Second Edition"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 115,
                            Author = "Marcus Aurelius",
                            CreationYear = "2018",
                            Genre = "Philosophy",
                            Price = 12.83m,
                            Title = "Meditations"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
